### This dataset contains information about various health and lifestyle factors of 100000 individuals

#### Columns:

id : Unique identifier <br>
age : Age of the person <br>
gender : Gender (Male/Female) <br>
bmi : Body Mass Index <br>
daily_steps : Number of steps per day <br>
sleep_hours : Average sleep duration (hours) <br>
water_intake_l : Daily water intake (liters) <br>
calories_consumed : Calories consumed per day <br>
smoker : Smoking status (0 = No, 1 = Yes) <br>
alcohol : Alcohol use (0 = No, 1 = Yes) <br>
resting_hr : Resting heart rate (bpm) <br>
systolic_bp : Systolic blood pressure<br>
diastolic_bp : Diastolic blood pressure<br>
cholesterol : Cholesterol level (mg/dL)<br>
family_history : Family history of disease (0 = No, 1 = Yes)<br>
disease_risk : Risk of disease (0 = Low, 1 = High)

In [1]:
%pip install pandas plotly
%pip install nbformat
%pip install streamlit pandas plotly
%pip install -U kaleido

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (2.0.1)
Requirement already satisfied: plotly in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (6.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/tanya/Library/Python/3.10/lib/python/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pandas) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pandas) (1.24.3)
Requirement already satisfied: narwhals>=1.15.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from plotly) (2.8.0)
Requirement already satisfied: packaging in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from plotly) (25.0)
Requirement already satisfied: six>=1.5 in /Users/tanya/Library/Python/3.10/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: pip3.10 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: nbformat in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (5.10.4)
Requirement already satisfied: fastjsonschema>=2.15 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from nbformat) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from nbformat) (4.25.1)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /Users/tanya/Library/Python/3.10/lib/python/site-packages (from nbformat) (5.3.0)
Requirement already satisfied: traitlets>=5.1 in /Users/tanya/Library/Python/3.10/lib/python/site-packages (from nbformat) (5.9.0)
Requirement already satisfied: attrs>=22.2.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from jsonschema>=2.6->nbformat) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from jsonschema>=2.6->nbformat) (0.27.1)
Requirement already satisfied: platformdirs>=2.5 in /Users/tanya/Library/Python/3.10/lib/python/site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (3.5.0)
Requirement already satisfied: typing-extensions>=4.4.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat) (4.15.0)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: pip3.10 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: streamlit in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (1.50.0)
Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (2.0.1)
Requirement already satisfied: plotly in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (6.3.1)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<6,>=4.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<7,>=4.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from streamlit) (6.2.1)
Requirement already satisfied: click<9,>=7.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from streamlit) (8.1.3)
Requirement already satisfied: numpy<3,>=1.23 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from streamlit) (1.24.3)
Requirement already satisfied: packaging<26,>=20 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from streamlit) (25.0)
Requirement already satisfied: pillow<12,>=7.1.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from streamlit) (9.5.0)
Requirement already satisfied: protobuf<7,>=3.20 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from streamlit) (6.32.1)
Requirement already satisfied: pyarrow>=7.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from streamlit) (21.0.0)
Requirement already satisfied: requests<3,>=2.27 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from streamlit) (2.32.5)
Requirement already satisfied: tenacity<10,>=8.1.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from streamlit) (9.1.2)
Requirement already satisfied: toml<2,>=0.10.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from streamlit) (4.15.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from streamlit) (3.1.45)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from streamlit) (0.9.1)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /Users/tanya/Library/Python/3.10/lib/python/site-packages (from streamlit) (6.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/tanya/Library/Python/3.10/lib/python/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pandas) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pandas) (2023.3)
Requirement already satisfied: jinja2 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (4.25.1)
Requirement already satisfied: narwhals>=1.14.2 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2.8.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests<3,>=2.27->streamlit) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests<3,>=2.27->streamlit) (2025.10.5)
Requirement already satisfied: MarkupSafe>=2.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.27.1)
Requirement already satisfied: six>=1.5 in /Users/tanya/Library/Python/3.10/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: pip3.10 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: kaleido in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (1.1.0)
Collecting kaleido
  Downloading kaleido-1.2.0-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: choreographer>=1.1.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from kaleido) (1.1.2)
Requirement already satisfied: logistro>=1.0.8 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from kaleido) (2.0.0)
Requirement already satisfied: orjson>=3.10.15 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from kaleido) (3.11.3)
Requirement already satisfied: packaging in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from kaleido) (25.0)
Requirement already satisfied: pytest-timeout>=2.4.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from kaleido) (2.4.0)
Requirement already satisfied: simplejson>=3.19.3 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from choreographer>=1.1.1->kaleido) (3.20.2)
Requirement already satisfied: pytest>=7.0.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pytest-timeout>=2.4.0->kaleido) (8.4.2)
Requirement already satisfied: exceptiongroup>=1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido) (1.3.0)
Requirement already satisfied: iniconfig>=1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido) (2.1.0)
Requirement already satisfied: pluggy<2,>=1.5 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido) (1.6.0)
Requirement already satisfied: pygments>=2.7.2 in /Users/tanya/Library/Python/3.10/lib/python/site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido) (2.15.1)
Requirement already satisfied: tomli>=1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido) (2.3.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from exceptiongroup>=1->pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido) (4.15.0)
Downloading kaleido-1.2.0-py3-none-any.whl (68 kB)
Installing collected packages: kaleido
  Attempting uninstall: kaleido
    Found existing installation: kaleido 1.1.0
    Uninstalling kaleido-1.1.0:
      Successfully uninstalled kaleido-1.1.0
Successfully installed kaleido-1.2.0

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: pip3.10 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,MinMaxScaler,StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC,LinearSVC
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [3]:
path = "/Users/tanya/Desktop/Data Science Journey/ML/my_project/health_lifestyle_dataset.csv"
df = pd.read_csv(path)

In [4]:
num_cols = df.shape[1]
num_rows = df.shape[0]
print(f"Number of columns: {num_cols} \nNumber of rows: {num_rows}")

Number of columns: 16
Number of rows: 100000

In [5]:
print("a glimpse into the dataset:")
df.head()

a glimpse into the dataset:

,id,age,gender,bmi,daily_steps,sleep_hours,water_intake_l,calories_consumed,smoker,alcohol,resting_hr,systolic_bp,diastolic_bp,cholesterol,family_history,disease_risk
0,1,56,Male,20.5,4198,3.9,3.4,1602,0,0,97,161,111,240,0,0
1,2,69,Female,33.3,14359,9.0,4.7,2346,0,1,68,116,65,207,0,0
2,3,46,Male,31.6,1817,6.6,4.2,1643,0,1,90,123,99,296,0,0
3,4,32,Female,38.2,15772,3.6,2.0,2460,0,0,71,165,95,175,0,0
4,5,60,Female,33.6,6037,3.8,4.0,3756,0,1,98,139,61,294,0,0

In [9]:
df.describe()

,id,age,bmi,daily_steps,sleep_hours,water_intake_l,calories_consumed,smoker,alcohol,resting_hr,systolic_bp,diastolic_bp,cholesterol,family_history,disease_risk
count,100000.000000,100000.000000,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000
mean,50000.500000,48.525990,29.024790,10479.87029,6.491784,2.751496,2603.341200,0.200940,0.300020,74.457420,134.58063,89.508850,224.300630,0.299150,0.248210
std,28867.657797,17.886768,6.352666,5483.63236,2.021922,1.297338,807.288563,0.400705,0.458269,14.423715,25.95153,17.347041,43.327749,0.457888,0.431976
min,1.000000,18.000000,18.000000,1000.00000,3.000000,0.500000,1200.000000,0.000000,0.000000,50.000000,90.00000,60.000000,150.000000,0.000000,0.000000
25%,25000.750000,33.000000,23.500000,5729.00000,4.700000,1.600000,1906.000000,0.000000,0.000000,62.000000,112.00000,74.000000,187.000000,0.000000,0.000000
50%,50000.500000,48.000000,29.000000,10468.00000,6.500000,2.800000,2603.000000,0.000000,0.000000,74.000000,135.00000,89.000000,224.000000,0.000000,0.000000
75%,75000.250000,64.000000,34.500000,15229.00000,8.200000,3.900000,3299.000000,0.000000,1.000000,87.000000,157.00000,105.000000,262.000000,1.000000,0.000000
max,100000.000000,79.000000,40.000000,19999.00000,10.000000,5.000000,3999.000000,1.000000,1.000000,99.000000,179.00000,119.000000,299.000000,1.000000,1.000000

Let's have a bird's eye view on the data using Plotly library

In [6]:
age = df["age"]
bmi = df["bmi"]
steps = df["daily_steps"]
sleep = df["sleep_hours"]
water = df["water_intake_l"]

calory = df["calories_consumed"]
rest = df["resting_hr"]
cholesterol = df["cholesterol"]
systolic_bp = df["systolic_bp"]
diastolic_bp = df["diastolic_bp"]

gender = df["gender"]
smoke = df["smoker"]
alcohol = df["alcohol"]
family_history = df["family_history"]
disease_risk = df["disease_risk"]

In [7]:
%pip install --upgrade kaleido

Requirement already satisfied: kaleido in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (1.2.0)
Requirement already satisfied: choreographer>=1.1.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from kaleido) (1.1.2)
Requirement already satisfied: logistro>=1.0.8 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from kaleido) (2.0.0)
Requirement already satisfied: orjson>=3.10.15 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from kaleido) (3.11.3)
Requirement already satisfied: packaging in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from kaleido) (25.0)
Requirement already satisfied: pytest-timeout>=2.4.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from kaleido) (2.4.0)
Requirement already satisfied: simplejson>=3.19.3 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from choreographer>=1.1.1->kaleido) (3.20.2)
Requirement already satisfied: pytest>=7.0.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pytest-timeout>=2.4.0->kaleido) (8.4.2)
Requirement already satisfied: exceptiongroup>=1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido) (1.3.0)
Requirement already satisfied: iniconfig>=1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido) (2.1.0)
Requirement already satisfied: pluggy<2,>=1.5 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido) (1.6.0)
Requirement already satisfied: pygments>=2.7.2 in /Users/tanya/Library/Python/3.10/lib/python/site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido) (2.15.1)
Requirement already satisfied: tomli>=1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido) (2.3.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from exceptiongroup>=1->pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido) (4.15.0)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: pip3.10 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [8]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots


data = {
    "Age": age,
    "BMI": bmi,
    "Daily steps": steps,
    "Sleep hours": sleep,
    "Water intake": water,
    "Calory consumption": calory,
    "Resting hour": rest,
    "Cholesterol": cholesterol,
    "Systolic blood pressure": systolic_bp,
    "Diastolic blood pressure": diastolic_bp,
    "Gender": gender,
    "Smoke": smoke,
    "Alcohol": alcohol,
    "Family history": family_history,
    "Disease risk": disease_risk
}


bin_specs = {
    "Age": dict(start=int(age.min()), end=int(age.max()) + 1, size=1),
    "BMI": dict(start=float(bmi.min()), end=float(bmi.max()), size=0.5),
    "Daily steps": dict(start=int(steps.min()), end=int(steps.max()), size=500),
    "Sleep hours": dict(start=int(sleep.min()), end=int(sleep.max()) + 1, size=1),
    "Water intake": dict(start=int(water.min()), end=int(water.max()) + 1, size=1),
    "Calory consumption": dict(start=int(calory.min()), end=int(calory.max()) + 1, size=300),
    "Resting hour": dict(start=int(rest.min()), end=int(rest.max()) + 1, size=5),
    "Cholesterol": dict(start=int(cholesterol.min()), end=int(cholesterol.max()) + 1, size=30),
    "Systolic blood pressure": dict(start=int(systolic_bp.min()), end=int(systolic_bp.max()) + 1, size=10),
    "Diastolic blood pressure": dict(start=int(diastolic_bp.min()), end=int(diastolic_bp.max()) + 1, size=10),
    "Gender": dict(start=-0.5, end=1.5, size=1),
    "Smoke": dict(start=-0.5, end=1.5, size=1),
    "Alcohol": dict(start=-0.5, end=1.5, size=1),
    "Family history": dict(start=-0.5, end=1.5, size=1),
    "Disease risk": dict(start=-0.5, end=1.5, size=1)
}

fig = make_subplots(rows=3, cols=5, subplot_titles=list(data.keys()))
positions = [(1,1), (1,2), (1,3), (1,4), (1,5), (2,1), (2,2), (2,3), (2,4), (2,5), (3,1), (3,2), (3,3), (3,4), (3,5)]

for (title, s), (r, c) in zip(data.items(), positions):
    xbins = bin_specs[title]
    fig.add_trace(
        go.Histogram(
            x=s,
            xbins=xbins,          
            histfunc="count",     
            histnorm=None,        
            marker=dict(color="#1f77b4", line=dict(color = "yellow", width=0.8))
        ),
        row=r, col=c
    )
    fig.update_xaxes(range=[xbins["start"], xbins["end"]], row=r, col=c)
    fig.update_yaxes(row=r, col=c)

fig.update_layout(
    height=800, width=1400,
    showlegend=False,
    title_text="Health Dataset Histograms",
    title_x=0.5,
    bargap=0.05
)

fig.add_annotation(
    text="Count",
    x=-0.05, y=0.5,
    xref="paper", yref="paper",
    showarrow=False,
    textangle=-90,
    font=dict(size=20)
)

fig.write_image("/Users/tanya/Desktop/Data Science Journey/ML/my_project/docs/histograms.png", scale=2)
fig.show()

In [12]:
encoder = LabelEncoder()
df['gender']=encoder.fit_transform(df['gender'])

In [13]:
df.head()

,id,age,gender,bmi,daily_steps,sleep_hours,water_intake_l,calories_consumed,smoker,alcohol,resting_hr,systolic_bp,diastolic_bp,cholesterol,family_history,disease_risk
0,1,56,1,20.5,4198,3.9,3.4,1602,0,0,97,161,111,240,0,0
1,2,69,0,33.3,14359,9.0,4.7,2346,0,1,68,116,65,207,0,0
2,3,46,1,31.6,1817,6.6,4.2,1643,0,1,90,123,99,296,0,0
3,4,32,0,38.2,15772,3.6,2.0,2460,0,0,71,165,95,175,0,0
4,5,60,0,33.6,6037,3.8,4.0,3756,0,1,98,139,61,294,0,0

##### now we will standardize the values of some columns to keep the scales of values similar to each other.

In [16]:
scaler = StandardScaler()
df['daily_steps'] = scaler.fit_transform(df[['daily_steps']])
df['calories_consumed']=scaler.fit_transform(df[['calories_consumed']])
df['cholesterol']=scaler.fit_transform(df[['cholesterol']])

In [17]:
df.head()

,id,age,gender,bmi,daily_steps,sleep_hours,water_intake_l,calories_consumed,smoker,alcohol,resting_hr,systolic_bp,diastolic_bp,cholesterol,family_history,disease_risk
0,1,56,1,20.5,-1.145573,3.9,3.4,-1.240382,0,0,97,161,111,0.362342,0,0
1,2,69,0,33.3,0.707405,9.0,4.7,-0.318774,0,1,68,116,65,-0.399299,0,0
2,3,46,1,31.6,-1.579777,6.6,4.2,-1.189594,0,1,90,123,99,1.654822,0,0
3,4,32,0,38.2,0.965082,3.6,2.0,-0.177560,0,0,71,165,95,-1.137859,0,0
4,5,60,0,33.6,-0.810210,3.8,4.0,1.427822,0,1,98,139,61,1.608662,0,0

In [18]:
df.drop(columns=['id'],inplace=True)

##### disease risk is our target class y and the rest will be our features x

In [19]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [20]:
x

,age,gender,bmi,daily_steps,sleep_hours,water_intake_l,calories_consumed,smoker,alcohol,resting_hr,systolic_bp,diastolic_bp,cholesterol,family_history
0,56,1,20.5,-1.145573,3.9,3.4,-1.240382,0,0,97,161,111,0.362342,0
1,69,0,33.3,0.707405,9.0,4.7,-0.318774,0,1,68,116,65,-0.399299,0
2,46,1,31.6,-1.579777,6.6,4.2,-1.189594,0,1,90,123,99,1.654822,0
3,32,0,38.2,0.965082,3.6,2.0,-0.177560,0,0,71,165,95,-1.137859,0
4,60,0,33.6,-0.810210,3.8,4.0,1.427822,0,1,98,139,61,1.608662,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,53,1,33.1,-1.049286,3.9,2.0,0.637518,0,1,56,105,76,1.331702,0
99996,22,1,35.1,0.195880,4.5,3.1,-0.788249,0,0,51,149,77,-0.745499,0
99997,37,1,18.9,-1.195540,3.8,1.0,-0.341071,0,0,69,92,117,-0.145419,0
99998,72,0,27.8,1.026721,5.6,0.8,0.606550,0,0,93,164,72,-0.837819,0
99999,37,1,35.4,-0.411749,9.1,1.8,1.658224,0,1,71,145,80,1.193222,0

In [21]:
y

0        0
1        0
2        0
3        0
4        0
        ..
99995    0
99996    0
99997    0
99998    0
99999    1
Name: disease_risk, Length: 100000, dtype: int64

##### splitting data to train and test

In [22]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

##### Logistic Regression

In [23]:
model=LogisticRegression(max_iter=1000)
model.fit(x_train,y_train)

LogisticRegression(max_iter=1000)

In [24]:
y_pred=model.predict(x_test)

In [25]:
print(confusion_matrix(y_test,y_pred))

[[15079     0]
 [ 4921     0]]

In [26]:
print(accuracy_score(y_test,y_pred)*100)

75.395